name: My first workflow

on: push

jobs:
    build_job:
       runs-on: ubuntu-latest
       steps: 
         - name: Checkout Repo
           uses: actions/checkout@v4

         - name: Install Cowsay
           run: sudo apt-get install cowsay -y

         - name: Execute cowsay cmd
           run: cowsay -f dragon "Run for cover, I am DRAGON....RAWR" >> dragon.txt

         - name: Execute the Script
           run:
             chmod +x script.sh

             ./script.sh

         - name: welcome to ubuntu
           run: echo "welcome to ubuntu"

    Test_job:
        runs-on: ubuntu-latest
        needs: build_job
        steps:
            - name: Read the files
              run: grep -i "dragon" dragon.txt

    Deploy_Job:
        runs-on: ubuntu-latest
        needs: Test_job
        steps:
            - name: Read file
              run: cat dragon.txt

            - name: Deployment status
              run: echo "Deployment completed"

    

   