name: My first workflow

on: push

jobs:
    first_job:
       runs-on: ubuntu-latest
       steps: 
         - name: Checkout Repo
           uses: actions/checkout@v4

         - name: Execute the Script
           run:
             ./script.sh

         - name: welcome to ubuntu
           run: echo "welcome to ubuntu"

    

   